### ISSUE TITLE
Environment introspection failures are not handled

### ISSUE THREAD

**Issue by mmarchetti** [rstudio/rsconnect-jupyter#144]
If introspection of the python environment fails, a JSON object with an `error` field is returned. The front end should report that error and stop the deployment. Instead, it passes the (invalid) environment description to the backend which fails with this error:

```
[E 14:52:45.406 NotebookApp] Bundle creation failed
    Traceback (most recent call last):
      File "/rsconnect_jupyter/rsconnect_jupyter/__init__.py", line 117, in post
        bundle = make_source_bundle(model, environment, ext_resources_dir, extra_files=[])
      File "/rsconnect_jupyter/rsconnect_jupyter/bundle.py", line 117, in make_source_bundle
        manifest = make_source_manifest(nb_name, environment, 'jupyter-static')
      File "/rsconnect_jupyter/rsconnect_jupyter/bundle.py", line 20, in make_source_manifest
        package_manager = environment['package_manager']
    KeyError: 'package_manager'
```

**Comment by joncfoo** [comment]
Closing in favor of #155
