### ISSUE TITLE
Uncaught exception POST /rsconnect_jupyter/app_search (::1) - Unhandled error

### ISSUE THREAD

**Issue by snamburi3** [rstudio/rsconnect-jupyter#170]
Hi, I am getting the following error message. I have check the logs on the server side as well and couldn't figure out why. Could you please help?
 

```
[E 18:04:55.199 NotebookApp] Uncaught exception POST /rsconnect_jupyter/app_search (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/rsconnect_jupyter/app_search', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/sn/jupyter-rstudio/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/sn/jupyter-rstudio/lib/python3.6/site-packages/tornado/web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "/home/sn/jupyter-rstudio/lib/python3.6/site-packages/rsconnect_jupyter-1.2.1.9999-py3.6.egg/rsconnect_jupyter/__init__.py", line 73, in post
        retval = app_search(uri, api_key, title, app_id)
      File "/home/sn/jupyter-rstudio/lib/python3.6/site-packages/rsconnect_jupyter-1.2.1.9999-py3.6.egg/rsconnect_jupyter/api.py", line 280, in app_search
        apps = api.app_find(filters)
      File "/home/sn/jupyter-rstudio/lib/python3.6/site-packages/rsconnect_jupyter-1.2.1.9999-py3.6.egg/rsconnect_jupyter/api.py", line 164, in app_find
        data = self.json_response()
      File "/home/sn/jupyter-rstudio/lib/python3.6/site-packages/rsconnect_jupyter-1.2.1.9999-py3.6.egg/rsconnect_jupyter/api.py", line 141, in json_response
        raw = response.read().decode('utf-8')
      File "/Users/sn/anaconda3/lib/python3.6/http/client.py", line 459, in read
        s = self.fp.read()
      File "/Users/sn/anaconda3/lib/python3.6/socket.py", line 586, in readinto
        return self._sock.recv_into(b)
      File "/Users/sn/anaconda3/lib/python3.6/ssl.py", line 1012, in recv_into
        return self.read(nbytes, buffer)
      File "/Users/sn/anaconda3/lib/python3.6/ssl.py", line 874, in read
        return self._sslobj.read(len, buffer)
      File "/Users/sn/anaconda3/lib/python3.6/ssl.py", line 631, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
[W 18:04:55.201 NotebookApp] Unhandled error
```

**Comment by joncfoo** [comment]
> socket.timeout: The read operation timed out

It looks like the plugin is failing to connect to the RStudio Connect server.  Could you verify that the machine where Jupyter Notebook is running can access the RStudio Connect server?

**Comment by snamburi3** [comment]
I believe the answer is yes. I am able to add the server without any errors. Do you suggest any tests to make sure? 

The curl with the API key from the same machine (my laptop) gives the 200 message:
r = requests.get( 'https://rserver.org/content/49/out.html', headers = { 'Authorization': 'Key [somekey]' })
<Response [200]>
This works only if the content is open internally. By the way, our RStudio Connect is an internal server, nothing is published publicly and does not have a external IP.

**Comment by mmarchetti** [comment]
Closing this as stale.
