### ISSUE TITLE
Python2 Installation Challenges

### ISSUE THREAD

**Issue by kgartland-rstudio** [rstudio/rsconnect-jupyter#304]
In virtualenv running python 2.7.17, I had some challenges installing and running the rsonnect-jupyter plugin.

Command: `make version-frontend && python setup.py install`
problem package: ipkernel 6.0.3

solution: add `ipykernel==4.9.0` to `setup.cfg`

<details><summary>error:</summary>

```
Best match: ipykernel 6.0.3
Processing ipykernel-6.0.3.tar.gz
Writing /var/folders/g_/6jb8mjm509bgp81hw_z2wyd40000gn/T/easy_install-9NWLrc/ipykernel-6.0.3/setup.cfg
Running ipykernel-6.0.3/setup.py -q bdist_egg --dist-dir /var/folders/g_/6jb8mjm509bgp81hw_z2wyd40000gn/T/easy_install-9NWLrc/ipykernel-6.0.3/egg-dist-tmp-JIvGSm
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    setup()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/Users/kgartland/.pyenv/versions/2.7.17/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/kgartland/.pyenv/versions/2.7.17/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/kgartland/.pyenv/versions/2.7.17/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/Users/kgartland/.pyenv/versions/2.7.17/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/kgartland/.pyenv/versions/2.7.17/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/g_/6jb8mjm509bgp81hw_z2wyd40000gn/T/easy_install-9NWLrc/ipykernel-6.0.3/setup.py", line 108, in <module>

  File "/var/folders/g_/6jb8mjm509bgp81hw_z2wyd40000gn/T/easy_install-9NWLrc/ipykernel-6.0.3/ipykernel/__init__.py", line 2, in <module>
  File "/var/folders/g_/6jb8mjm509bgp81hw_z2wyd40000gn/T/easy_install-9NWLrc/ipykernel-6.0.3/ipykernel/connect.py", line 12, in <module>
  File "build/bdist.macosx-10.15-x86_64/egg/jupyter_client/__init__.py", line 6, in <module>
  File "build/bdist.macosx-10.15-x86_64/egg/jupyter_client/asynchronous/__init__.py", line 1, in <module>
  File "build/bdist.macosx-10.15-x86_64/egg/jupyter_client/asynchronous/client.py", line 6, in <module>
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/jupyter_client-7.0.0a0-py2.7.egg/jupyter_client/channels.py", line 47
    time_to_dead: float = 1.0
```

</details>

Command: `jupyter-nbextension install --sys-prefix --py rsconnect_jupyter`
problem package: tornado

solution: `pip install tornado==5.0`
<details><summary>error:</summary>

```
Traceback (most recent call last):
  File "/Users/kgartland/.pyenv/versions/python2/bin/jupyter-nbextension", line 11, in <module>
    load_entry_point('notebook==5.7.10', 'console_scripts', 'jupyter-nbextension')()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/notebook-5.7.10-py2.7.egg/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/notebook-5.7.10-py2.7.egg/notebook/nbextensions.py", line 610, in <module>
    from .extensions import (
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/notebook-5.7.10-py2.7.egg/notebook/extensions.py", line 8, in <module>
    from tornado.log import LogFormatter
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/tornado-6.1-py2.7-macosx-10.15-x86_64.egg/tornado/log.py", line 55
    def _stderr_supports_color() -> bool:
                                 ^
SyntaxError: invalid syntax
```
</details>

Command: `jupyter notebook`
problem package: jupyter-client

solution: `pip install jupyter-client==5.3.5`

<details><summary>error:</summary>

```
Traceback (most recent call last):
  File "/Users/kgartland/.pyenv/versions/python2/bin/jupyter-notebook", line 11, in <module>
    load_entry_point('notebook==5.7.10', 'console_scripts', 'jupyter-notebook')()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/notebook-5.7.10-py2.7.egg/notebook/notebookapp.py", line 81, in <module>
    from .services.kernels.kernelmanager import MappingKernelManager
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/notebook-5.7.10-py2.7.egg/notebook/services/kernels/kernelmanager.py", line 19, in <module>
    from jupyter_client.session import Session
  File "build/bdist.macosx-10.15-x86_64/egg/jupyter_client/__init__.py", line 6, in <module>
  File "build/bdist.macosx-10.15-x86_64/egg/jupyter_client/asynchronous/__init__.py", line 1, in <module>
  File "build/bdist.macosx-10.15-x86_64/egg/jupyter_client/asynchronous/client.py", line 6, in <module>
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/jupyter_client-7.0.0a0-py2.7.egg/jupyter_client/channels.py", line 47
    time_to_dead: float = 1.0
                ^
SyntaxError: invalid syntax
```
</details>

Command: `jupyter notebook`
problem package: terminado

solution: `pip install terminado==0.8.3`
<details><summary>error:</summary>

```
Traceback (most recent call last):
  File "/Users/kgartland/.pyenv/versions/python2/bin/jupyter-notebook", line 11, in <module>
    load_entry_point('notebook==5.7.10', 'console_scripts', 'jupyter-notebook')()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/notebook-5.7.10-py2.7.egg/notebook/notebookapp.py", line 1631, in initialize
    self.init_terminals()
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/notebook-5.7.10-py2.7.egg/notebook/notebookapp.py", line 1458, in init_terminals
    from .terminal import initialize
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/notebook-5.7.10-py2.7.egg/notebook/terminal/__init__.py", line 3, in <module>
    import terminado
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/terminado-0.10.1-py2.7.egg/terminado/__init__.py", line 8, in <module>
    from .management import (TermManagerBase, SingleTermManager,
  File "/Users/kgartland/.pyenv/versions/python2/lib/python2.7/site-packages/terminado-0.10.1-py2.7.egg/terminado/management.py", line 87
    async def terminate(self, force=False):
            ^
SyntaxError: invalid syntax
```

</details>

**Comment by kgartland-rstudio** [comment]
Closing as these errors went away when installing via pip which is how customers will install rsconnect-jupyter.
